### ISSUE TITLE
Crash on startup after removing empty mip maps

### ISSUE THREAD

**Issue by sanctibus** [MassEffectModder/MassEffectModder#10] opened 2017-01-22 14:29 UTC
After removing the maps Mass Effect 3 always crashes on startup. I have to redownload the files from Origin to get the exe to work again. I'm trying to install ALOT. Furthermore the game creates a log file. I don't know if it helps to resolve the issue but I attached the .txt Log file just in case it is needed.
[ME3Log.txt](https://github.com/MassEffectModder/MassEffectModder/files/721987/ME3Log.txt)

**Comment by aquadran** [comment] 2017-01-22 14:36
So, you have re-downloaded the files from Origin and after removal mipmaps is still crashing?

**Comment by aquadran** [comment] 2017-01-22 14:48
Do you have any DLC mods installed?

**Comment by sanctibus** [comment] 2017-01-22 14:48
No. After redownloading I'm able to launch the game normally. I'm also using Flawless Widescreen and Reshade but disabled them so that I could give you an accurate bug report. They are not causing the crashes so I just leave them enabled for now. Additionally I deleted the gamersettings.ini. Still no change.
If it helps I'm using various DLC Mods like EGM Back-Off ME3RE and Expanded Anderson Conversation.  On  the ALOT forum I read that MassEffectModder is 100% compatible with every DLC Mod so I haven't tried to install the textures in a complete vanilla enviornment. I will do so now and report back. Do you have any other ideas why this could be happening? I tried to install the textures via ME3Explorer but I get black vanilla textures

**Comment by aquadran** [comment] 2017-01-22 14:54
"via ME3Explorer but I get black vanilla textures" you have to revert gamersettings.ini changes, so delete file or use MEM menu option: "Remove LODs settings".
I guess, you followed order? vanilla game->install mods->scan textures->install textures->remove mipmaps->update lods

**Comment by sanctibus** [comment] 2017-01-22 15:03
Yep I followed the instructions. I tried ME3Explorer after using your tool. I already deleted my gamersettings.ini but it still won't launch. Unrelated to this issue but if i click on "Remove LODs settings" in MEM I'm asked to select the ME2 .exe. Is that supposed to be like this? Note that the crashs always happen after I remove the empty mip maps. But if I don't remove them i get the aforementioned black vanilla textures.

**Comment by aquadran** [comment] 2017-01-22 15:20
deleting gamersettings.ini it's for black textures in ME3 if you install textures with ME3Explorer.
What you mean you tried use ME3Explorer after?
Asking for ME2 it seems a bug, I'll check that.
If you could try without installing DLC mods, we would know it's caused by DLC mods.

**Comment by sanctibus** [comment] 2017-01-22 15:31
I'm reinstalling right now should be done in 10 minutes. About ME3Explorer: After I used MEM and experienced the crashes i uninstalled Mass Effect 3. Then I tried to install the textures with ME3Ex and I got black Textures. I never got black Textures with ME3ex before so I thought maybe MEM changed some vital files. But I think it was just the gamersettings.ini. I'll report back after trying to install textures in complete vanilla environment

**Comment by aquadran** [comment] 2017-01-22 15:40
I fixed that ME2 issue. Will be included at next release. Removing Lods settings in MEM for ME3 propably not worked because of this.

**Comment by sanctibus** [comment] 2017-01-22 15:56
Good Job on fixing that! I just reinstalled everything and I guess our suspicions were right: Now the game starts up fine. I just installed EDI's textures. She hasn't changed in game (well at least I think so She looks normal and from the screenshots on nexus EDI has a complete different look). I don't really know which mod caused the crash but I heavily suspect this one: http://www.nexusmods.com/masseffect3/mods/439/?. I will proceed to add mods one by one now and confirm whether I'm right or not. Thanks for helping me troubleshoot this blatantly obvious issue. Sorry for taking up your time!

**Comment by aquadran** [comment] 2017-01-22 16:24
I think I didn't tested interface mod yet. I tested only that which users reports issues.

**Comment by sanctibus** [comment] 2017-01-22 16:45
Yup I just tested it and it's 100% this mod. I don't know why it doesn't work with the scaling mod but it just seems to be that mem and Interface scaling mod are incompatible.

**Comment by aquadran** [comment] 2017-01-22 17:06
ok, I'll look into, thanks for checking this

**Closed** 2017-01-22 17:07 UTC

**Comment by aquadran** [comment] 2017-01-30 19:15
interface mod should be fixed in 1.65
